/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

/**
 *
 * @author BEDI
 */
import java.sql.*;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import java.util.Vector;
import javax.swing.table.*;

public class AdminInterface extends javax.swing.JFrame {
        JLabel checkpoint=new JLabel();
        ImageIcon img=new ImageIcon();
        int press=0;
        int counter=0;
        int x=0;
        int y=0;
    /**
     * Creates new form AdminInterface
     */
    public AdminInterface() {
        initComponents();
        table();
        combobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        cab_details = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fare = new javax.swing.JTextField();
        speed = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        maintenance = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        tos = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        source = new javax.swing.JComboBox();
        destination = new javax.swing.JComboBox();
        currentc = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        cabs = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("New Vehicle");

        jLabel2.setText("Type");

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ac", "Non-Ac" }));

        jLabel4.setText("Source");

        jLabel3.setText("Destination");

        jLabel5.setText("Start Position");

        jLabel7.setText("Fare/Km");

        jLabel8.setText("Avg. Speed");

        speed.setText("40");
        speed.setFocusable(false);

        jLabel9.setText("Maintenance Details");

        maintenance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Up to Date", "Required" }));

        jLabel10.setText("Type of Service");

        tos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Shared" }));

        jButton1.setText("ADD");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cab_detailsLayout = new javax.swing.GroupLayout(cab_details);
        cab_details.setLayout(cab_detailsLayout);
        cab_detailsLayout.setHorizontalGroup(
            cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cab_detailsLayout.createSequentialGroup()
                .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cab_detailsLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(source, 0, 103, Short.MAX_VALUE)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destination, 0, 103, Short.MAX_VALUE)
                            .addComponent(currentc, 0, 103, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cab_detailsLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(speed)
                                    .addComponent(fare, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                            .addGroup(cab_detailsLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(cab_detailsLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jButton2)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)
                        .addGap(40, 40, 40)
                        .addComponent(jButton3)))
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cab_detailsLayout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(252, 252, 252))
        );
        cab_detailsLayout.setVerticalGroup(
            cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cab_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(fare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(maintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(cab_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        cabs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        cabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cabsMouseClicked(evt);
            }
        });
        cabs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cabsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cabsFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(cabs);

        jMenu1.setText("File");

        jMenuItem2.setText("New");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Map");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1189, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(cab_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cab_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1215)/2, (screenSize.height-660)/2, 1215, 660);
    }// </editor-fold>//GEN-END:initComponents
public void combobox()
{
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cabservice", "root", "");
        Statement stat=con.createStatement();
        ResultSet r=stat.executeQuery("SELECT * FROM location");
        while(r.next())
        {
            source.addItem(r.getString("name"));
            destination.addItem(r.getString("name"));
            currentc.addItem(r.getString("name"));
        }
    }catch(Exception e)
    {
        System.out.println(e);
    }
}

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        int x=0;
        try {
            String currentcord="";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cabservice", "root", "");
            Statement stat=con.createStatement();
            ResultSet r=stat.executeQuery("SELECT * FROM location WHERE name='"+currentc.getSelectedItem().toString()+"'");
            if(r.next())
            {
                currentcord=r.getString("x")+","+r.getString("y");
            }
            stat.executeUpdate("INSERT INTO cab_details (source,destination,current,speed,fare,type,tos,maintainance) VALUES('"+source.getSelectedItem().toString()+"','"+destination.getSelectedItem().toString()+"','"+currentcord+"','"+fare.getText()+"','"+speed.getText()+"','"+type.getSelectedItem().toString()+"','"+tos.getSelectedItem().toString()+"','"+maintenance.getSelectedItem()+"')");
            JOptionPane.showMessageDialog(null, "Detail Added");
            table();
        }catch(Exception e) {
            System.out.println(e);
        }
}//GEN-LAST:event_jButton1MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        citythread frame=new citythread();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:

        if(cabs.getSelectedRow()!=-1);
        {
            String currentcord="";
            try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cabservice", "root", "");
            Statement stat=con.createStatement();
            ResultSet r=stat.executeQuery("SELECT * FROM location WHERE name='"+currentc.getSelectedItem().toString()+"'");
            if(r.next())
            {
                currentcord=r.getString("x")+","+r.getString("y");
            }
            stat.executeUpdate("UPDATE cab_details SET source='"+source.getSelectedItem()+"',destination='"+destination.getSelectedItem()+"',current='"+currentcord+"',speed='"+speed.getText()+"',fare='"+fare.getText()+"',type='"+type.getSelectedItem()+"',tos='"+tos.getSelectedItem()+"',maintainance='"+maintenance.getSelectedItem()+"' WHERE id='"+cabs.getValueAt(cabs.getSelectedRow(), 0)+"'");
            JOptionPane.showMessageDialog(null, "Details Updates");
            type.setSelectedItem(0);
            maintenance.setSelectedItem(1);
            tos.setSelectedItem(0);
            source.setSelectedIndex(0);
            destination.setSelectedIndex(0);
            fare.setText(null);
            speed.setText(null);
            table();
            }catch(Exception e) {
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void cabsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cabsFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cabsFocusGained

    private void cabsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabsMouseClicked
        // TODO add your handling code here:
                int i=cabs.getSelectedRow();
                int j=0;
        if(i==-1)
        {
            JOptionPane.showMessageDialog(null, "No Row Selected !");
        }
        else
        {
            if(cabs.getValueAt(i, 4).toString().equals("Ac"))
            {
                type.setSelectedIndex(0);
            }
            else
            {
                type.setSelectedIndex(1);
            }
            source.setSelectedItem(cabs.getValueAt(i, 1).toString());
            destination.setSelectedItem(cabs.getValueAt(i, 1).toString());

            try
            {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cabservice", "root", "");
            Statement stat=con.createStatement();
            ResultSet r=stat.executeQuery("SELECT * FROM location WHERE x="+Integer.parseInt(cabs.getValueAt(i, 3).toString().substring(0,cabs.getValueAt(i, 3).toString().indexOf(",")))+" AND y="+Integer.parseInt(cabs.getValueAt(i, 3).toString().substring(cabs.getValueAt(i, 3).toString().indexOf(",")+1))+"");
            if(r.next())
            {
                currentc.setSelectedItem(r.getString("name"));
            }
            }catch(Exception e)
            {
                System.out.println(e);
            }
            fare.setText(cabs.getValueAt(i, 5).toString());
            speed.setText(cabs.getValueAt(i, 6).toString());
            if(cabs.getValueAt(i, 7).toString().equals("Required"))
            {
                maintenance.setSelectedIndex(1);
            }
            else
            {
                maintenance.setSelectedIndex(0);
            }
            if(cabs.getValueAt(i, 8).toString().equals("Single"))
            {
                tos.setSelectedIndex(0);
            }
            else
            {
                tos.setSelectedIndex(1);
            }
        }
    }//GEN-LAST:event_cabsMouseClicked

    private void cabsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cabsFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cabsFocusLost

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        int i=cabs.getSelectedRow();
        if(i==-1)
        {
            JOptionPane.showMessageDialog(null, "No Row Selected !");
        }
        else
        {
            try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cabservice", "root", "");
            Statement stat=con.createStatement();
            stat.executeUpdate("DELETE FROM cab_details WHERE id='"+cabs.getValueAt(i, 0)+"'");
            JOptionPane.showMessageDialog(null, "Row Deleted Successfully");
            table();
            }catch(Exception e)
            {
                System.out.println(e);
            }
        }

    }//GEN-LAST:event_jButton3MouseClicked
        public  void table()
        {
            String col[]={"ID","Source","Destination","Start Position","Type","Fare","Avg.Speed","Maintenance Details","Type of Service"};
            Vector data=new Vector();
            DefaultTableModel model=new DefaultTableModel(null,col);
            cabs.setModel(model);
            try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cabservice", "root", "");
            Statement stat=con.createStatement();
            ResultSet r=stat.executeQuery("SELECT * FROM cab_details ORDER BY id DESC");
            while(r.next())
            {
                data=new Vector();
                data.addElement(r.getString("id"));
                data.addElement(r.getString("source"));
                data.addElement(r.getString("destination"));
                data.addElement(r.getString("current"));
                data.addElement(r.getString("type"));
                data.addElement(r.getString("fare"));
                data.addElement(r.getString("speed"));
                data.addElement(r.getString("maintainance"));
                data.addElement(r.getString("tos"));
                System.out.println(data);
                model.insertRow(0, data);
            }
        }catch(Exception e) {
            System.out.println(e);
        }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AdminInterface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel cab_details;
    private javax.swing.JTable cabs;
    private javax.swing.JComboBox currentc;
    private javax.swing.JComboBox destination;
    private javax.swing.JTextField fare;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox maintenance;
    private javax.swing.JComboBox source;
    private javax.swing.JTextField speed;
    private javax.swing.JComboBox tos;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
}
